services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
        - ./.env.docker
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
        - db:/app/database/sqlite
volumes:
  db:
    driver: local
